FROM httpd:2.4

EXPOSE 80

WORKDIR /usr/local/apache2/htdocs/ 

COPY *.html /usr/local/apache2/htdocs/ 
COPY script.js /usr/local/apache2/htdocs/ 
COPY cofetarie.pdf /usr/local/apache2/htdocs/
COPY style.css /usr/local/apache2/htdocs/